name: Create Branch

on:
  workflow_dispatch:  # This allows you to trigger the workflow manually

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Job name 01
        uses: actions/checkout@v2
        with:
          ref: main  # Adjust this if your main branch is named differently

      - name: This is job name
        run: |
          NEW_BRANCH="new-branch-name"  # Replace with your desired branch name
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
