name: Merge Feature to Promotion

on:
  push:
    branches:
      - 'feature/*'  # Trigger on any branch that starts with 'feature/'
  workflow_dispatch:  # This allows you to trigger the workflow manually

jobs:
  merge-feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # Check out the feature branch that triggered the workflow

      - name: Checkout the promotion branch
        run: |
          git fetch origin
          git checkout new-branch-name  # Checkout the actual promotion branch
          git pull origin new-branch-name  # Pull the latest changes from the remote

      - name: Merge feature branch into promotion branch
        run: |
          git merge ${{ github.ref }} --no-ff --allow-unrelated-histories -m "Merging changes from feature branch ${{ github.ref }} into new-branch-name" || { echo "Merge conflict occurred. Please resolve conflicts in the new-branch-name branch."; exit 1; }
          git push origin new-branch-name  # Push the updated promotion branch

      - name: Create Pull Request
        if: success()  # Only create a PR if the merge was successful
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Promote changes from new-branch-name to main"
          body: "This PR merges changes from the new-branch-name into main."
          base: main
          head: new-branch-name  # Use the actual promotion branch name
