name: Merge Feature to Promotion

on:
  push:
    branches:
      - 'feature/*'  # Trigger on any branch that starts with 'feature/'
  workflow_dispatch:  # This allows you to trigger the workflow manually

jobs:
  merge-feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # Check out the feature branch that triggered the workflow

      - name: Checkout the promotion branch
        run: |
          git fetch origin
          git checkout new-branch-name  # Checkout the actual promotion branch
          git pull origin new-branch-name  # Pull the latest changes from the remote

      - name: Attempt to Merge Feature Branch
        run: |
          if git merge ${{ github.ref }} --no-ff --allow-unrelated-histories; then
            git push origin new-branch-name
          else
            echo "Merge conflict detected. Creating pull request for manual resolution."
            exit 1  # Fail the job so the workflow stops here
          fi

      - name: Create Pull Request
        if: failure()  # Only run this step if the previous step failed
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Resolve merge conflicts between feature branch and new-branch-name"
          body: "Merge conflicts detected. Please resolve manually."
          base: new-branch-name
          head: ${{ github.ref }}  # The feature branch that triggered the workflow
