name: Merge Feature to Promotion

on:
  push:
    branches:
      - 'feature/*'  # Trigger on any branch that starts with 'feature/'
  workflow_dispatch:  # This allows you to trigger the workflow manually

jobs:
  merge-feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # Check out the feature branch that triggered the workflow

      - name: Checkout the new-branch-name
        run: |
          git fetch origin
          git checkout new-branch-name  # Replace with your actual new-branch-name name
          git pull origin new-branch-name

      - name: Merge feature branch into new-branch-name
        run: |
          git merge ${{ github.ref }} --no-ff -m "Merging changes from feature branch ${{ github.ref }} into new-branch-name"
          git push origin new-branch-name  # Replace with your actual new-branch-name name

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Promote changes from new-branch-name to main"
          body: "This PR merges changes from the new-branch-name into main."
          base: main
          head: new-branch-name  # Replace with your actual new-branch-name name
